[package]
name = "securitymonkey_crawler"
version = "0.1.0"
authors = ["indiv0"]
edition = "2018"

[dependencies]
reqwest = "0.10.8"
tokio = { version = "0.2.22", features = ["macros"] }
select = "0.5.0"
